name: FreezePlugin
version: '1.0'
main: com.nova.freezeplugin.FreezePlugin
authors: [TheTrueNova]
description: freeze plugin
website: https://discord.gg/tVDW7NeqPv
commands:
  freeze:
    aliases:
      - ss
      - screenshare
    description: Use this command to freeze someone.
  unfreeze:
    description: Use this to unfreeze someone who is frozen.
  request:
    aliases:
      - support
      - help
    description: Request support from online staff members.